# Generated by Django 4.1.1 on 2022-10-01 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtweetapp', '0003_commentvideo_commenttweet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commenttweet',
            old_name='tweet_id',
            new_name='tweet',
        ),
        migrations.RenameField(
            model_name='commentvideo',
            old_name='video_id',
            new_name='uploadedvideo',
        ),
    ]
